---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-secrets
  namespace: tools
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgBP/yaWZkhVBdCN2pphJ79IWGr3Rzo2paVrQXxkDTrAXXI7w9m2BSTjpg7X7VQHfXCXQeJRE2zCqtfv6Tn/NMoiikMVQr7dCZL77UBw6hGucOEYyeoegHOeEm/B2FVs1xNSIhsbPOnCpe2A1MqWbEHpXjB+2lFdg7yjcggvy0jnl74xUwap2MwTzpQMnF+IrWkxLtFmYPbk+RWXABkzAymjHQRyloQOtxt2yG6YNiUKSfYXynFFDdROeygSrtttnIUKGs+Aglo0zPtq7kjeGzkqTYlSfKF/MUAqcN5/3mDHgEAbhhsfijXgb9ZpzwQadn3idPGu36eJz9nMZOlHzQeK6slpC5oaTnBvnmKMWasHZKzApK3uyv/f1G4xkygf/mu6A7fwoNUc6bWc3oaX0OrR+4ZP3imWwXqWQaGUQyHe+0yqf3+OXmp6I1kpsXuF4IFn2pUP0RKJrePUQoz83g1nNUATi+gMbfG1uXzJvBA19ZtCIJKOKrI6HpEoIVP94W5pgK3+0ts0a/t9oj9Tt6hiJAl//XGLMzQ5hMSE4RrPT0VWMBIeGFlFCJ20EiPtgMj4lIxU42WswBB++SNP9ifQPobYzHWGibvNnmDMqY0hNWLYFzEf/oqmNFe/Mroaslxt5L/HkqSwCOHDdHF1rdsntKtjLrb82DlvQZqU1wzneBA91TH2KFOKilPYLbFlJUU0Tej5VdR5bMOk3jG93FyGJrptsu3gmcD8z78eDP9sn8U8oU/bxrdoNCAB/jTvLeUBy0WJ4SaKoWYXw7ey3DzQ
  template:
    metadata:
      name: karakeep-secrets
      namespace: tools
