apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: grafana-pv
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume1/Metrics/Grafana
    server: 10.0.0.146
---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: alert-manager-pv
  name: alert-manager-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume1/Metrics/AlertManager
    server: 10.0.0.146

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: prometheus-pv
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume1/Metrics/Prometheus
    server: 10.0.0.146

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: prometheus-operator-pv
  name: prometheus-operator-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume1/Metrics/Prometheus-Operator
    server: 10.0.0.146

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: prometheus-node-pv
  name: prometheus-node-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /volume1/Metrics/Prometheus-Node
    server: 10.0.0.146
