apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n8n
  name: n8n
spec:
  selector: 
    matchLabels:
      app: n8n
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers: 
        - name: n8n
          image: n8nio/n8n:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 5678
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          resources:
            limits: 
              memory: 2048M
              cpu: "500m"
          volumeMounts:
            - name: n8n-storage
              mountPath: /home/node/.n8n
              subPath: n8n/data
          
      volumes:
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-storage-claim
      restartPolicy: Always
      serviceAccount: n8n

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-storage
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "longhorn"
  csi:
    driver: driver.longhorn.io
    volumeHandle: n8n-longhorn-storage
    fsType: ext4


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 2Gi
  volumeName: n8n-storage


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: n8n
  name: n8n
spec:
  ports:
    - name: website
      port: 5678
      protocol: TCP
      targetPort: 5678
  selector:
    app: n8n


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n

