apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alfred
  name: alfred
spec:
  selector:
    matchLabels:
      app: alfred
  replicas: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alfred
    spec:
      containers: 
        - name: alfred
          image: localhost:31000/alfred
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          resources:
            limits:
              cpu: 500m
              memory: 512M # 1GB Memory
          ports:
            - containerPort: 8000
      restartPolicy: Always
      serviceAccount: alfred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alfred
  name: alfred
spec:
  clusterIP: 10.43.92.54
  ports:
    - name: http-alfred
      port: 80
      targetPort: 8000
  selector:
    app: alfred


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alfred
