apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-system
  labels:
    app: cloudtunnel
  name: cloudtunnel
spec:
  selector:
    matchLabels:
      app: cloudtunnel
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cloudtunnel
        network-policy: tunnel
    spec:
      nodeName: media
      # https://stackoverflow.com/questions/49368047/what-is-the-equivalent-for-depends-on-in-kubernetes
      containers: 
        - name: tunnel
          image: cloudflare/cloudflared:latest
          imagePullPolicy: "Always"
          args: 
            - tunnel
            - run
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          envFrom:
            - secretRef:
                name: cloudflare-tunnel-token
          # resources:
          #   limits:
          #     cpu: 200m
          #     memory: 512M 
      restartPolicy: Always
      serviceAccount: cloudtunnel


---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: istio-system
  name: cloudtunnel
