---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAJ9b+B1qA9RD/YcSDfAek7ihy09wd3x6bKc/nDz7MAWnUs1UNAHjw4yoptU9p8pc3h0aRutrnAxv1B9SI4OKl/8X4wtQ/DTBIp9a44bwqHuGAxCggey6fUM20YwoSW1HB39spWnn4EsnMfW7+95/jb/rUPkDCcFcsEQLNBbT2QriFy30K8rbAgpfyDOlPPRct9xu7wyYUWhv23TVSvYD3rbMmWZ4trVzCLKHvca/kDbsrJBw6oJZHVzdWSgE1Ldz+zEF5t3RdIX5aRZlwKJF2wFFQxGJFbj2WnkqiDd9SPrTIEHW6ALMhNWHMoNW/FcgDWuiyb5UkT/UuyHIb0u0Ry/d7dvR7rAQJ0PUcEvVozJUDhARvn5Y6yg7+ikzHURwL2eiCmphGIqLyn6nSRynUHqM5Ztw3WOxsACJzikPFcd8YBO1dMCiyhlwk793lsxcBmW+wjzuAqHjlqAto86XnxP65kSa/6NHFE9eFXQEulztUUGwTOK0A2A/THEiHw2opVhTZ+jcgdiu15+OY3gqe0J1534oQF+jRfQ8Aw3A/ALbrY8ieNTHCQWSvPvJ5Zi/3ykJ3hyXnyiX/2FGzEKRjU0LmPntSAXl3atGc3ePcXq4wuKvd6birCPa80Z6mSJKWllhkZp2h+RHSK4+8YXqfMprkI8dh74ibNX9UV+uYcZHDyc9I4yowdBcNech8cd0q+5lTWWsK6Ri6Zxor9zj+Hvqcv+UtEdS170NlWtHdUqRQYjHjJPLUm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
