---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: media
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAxbtfwAnYOBxGUr+nfd+jrJ1keotF8kfqOoSTvsGkq9KQtc6zHgC824ZaTh+tWes410tLpQSrcpLTeh65BiyZvj2VFKxDyYR07pdjJUsQHv3U/xx8M43smRRRbdVpPPWunU9UpnzjTRStJ9mODwBAsDS9vOvRMJEKgb34Ril4owM/Txg/PmKVGFqN71HnEioXaADvHyNClHi/jsE/bNeajZbd25vuxBEqFCR2haydJae8OLJrY4ho6Y4ghQlrHZRn9EPwvB9k/jeCDliCvuYWK9M60y48C02NSro+pWIoJp3NRQdnqa6uZNKS5S0fYVF3VhO/AqL61a5dETYLCydsi4GMLcyea27WqruyntMVZK/0GXFNj4pciPg1SkgmVCY+AugNNyxj0b//H/4s1CttS5k6IBxy2XkYoHWs39wyr5MEy/ZnW1/MZBE+FAEjTo16RhB+5CdkNl1nvVghTisyvCiiQMyy1iXpLQrEczZKgnWCR59i3m9Cx/vdfvnpRX+AX5yRQ8o7OpYX0MhA1hOVe0AJ6mGIRb+42nIytK/v9QJo/uhdnNJKWWapJnDWEMmzvY8IAY+Jzsin46hFtNFeamdX7oJhLvPD1EHrqKlmICo4n6GhtZ5DGepoQwFafbBXrbYslh9XqoB0rWJyFmIPqaU2j2KQNcZMjrzZOpoWvcOMX2ckPEO1v+piiceAN/sjJOY/0Kk1PIBHT0L/wG+Qi+l18aXBOqnSBZxrX5pNnHqildgwyx0eBC1b+W0+z7AycBt7JJwW1NVcKAmsQfJg242qiVoxawYpSNByKr5Kh6Y4gOlMBx8hAy5kddRrelwAqn9x9uGsltnSb5F9ktV9OSHZkH+CCkvh159jZokCPJ0cnxPVql6mMkaTbwjyrFPH8qv72czdP6aU8/lE9P1KqGsoFMWWTWOTkABkkDUCU6mDn8wmrQlZ7
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: media
