---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCvE+0GSrAxj1NZzcwtQm5EsKRi6FDRZGUmhv/PivKi9B8EUX2e/k7P9smdgFn/4pkr/zlmhzsmfUzZ2gqeX9RMQalOGcmpuYwOR3Z1/4h4eNRvz/LXzZZPQPEPrxDCIn5jizB9QKR7Y6WmSqC3Wwf84ghRrDgXbF6J19S6UrvfQ/3aUbs+KwIHa5cX1lJ/hS6oyOxdbnh2cIcmXQCMn9QRcd+QvufeHyJMxv2RyXFNIz2Ly8zypbzJpYnRBAbPMy3FNzVhs+ivDDFW1pjWMOXpgYhSFVcjMnGvfjd9Mv6WcBS+YD0Mb78iVKeq907QxQ5PCeKSl5QNMhV7JYcvBlSOALMBItj07073U/ve2Y6ZN8qXUtiW+3CZ6pI1UWp6V9ZNpZHudBO5opbTppN22MqerIcB/1w/Jw0OXbIyUixrVovu/t+6CXIVcYiIa5Bhcra5vLu+oUgZvFQi1b5pXswep8Z1uM+yUdbNS/Qdayi//bzwMnfk41x+l41afEV9KAxVNmZPGG806xVtolmss3vIcPBM03AT7Alt41pfBX/kwgoYkg/dcXSXfNbF8G570gHQ+O6D3iwviYe6/hczQjSkold/ka226IphICA++QdjDQ2R8dW1EUiZxzT9x3Hwtl1ujSoEGHwsCln9YKSRseDRYUz5LVTWYBJjw+K19HM5fJ13qtiS5wDCPHv/cf4t/0dfxnFPFuRGsv6YsBwcm/aRG7AK
    admin-user: AgAGVkQO9Nt9nEZDVLb8v/xDckVqZSlQX91SJB7yTtSNfnz+ruNQlZjZDgLlo5xdF8gOcdftEcpgbPkjMGcszzrd+D6Ev34a6yidxd8YpvlnsGjKBkmho96IM36TR0sU1OjhlMSldZPol/xUVkgVHGeXnirT4KtCAUShkQdJCpTsWJLeGiELd3hbR8ztJactQ3IUkpLTwYDswxJbWvIanZg/DNbAojZ7qCHDitjQ22139m/hg6Nx69XbNdnE71dct9W5iiRQskgIOuQiHQ/ar5VFRBd3AOrNTX3bM6CktD6GndX/3/ZAd5zoTJRmi3zvDB67uB1Mk3eaxDc4qpQz6xNvGKE9MI6hqbZLKd+Qh8Ujyi57xhw1OzYlvJbIK7NXH/5OUEMzbBYGCy5cGznAFIRjOXOrVOhljSHH1l/QblTLgp9EgJdpen7jik9yvhW21deqXm178lEuw3lB9WYEI7BXePKrZ9BA6LPNyAnOkNhOpcD49XwahUBVs21hlgk7qCwu5GkehaseeQOiDAsHjPbaW2BDaecC6VPiq4F2cknew1u1q+0TfRrKhRMO6ebCYdOgGkUrEhqY7l2x9fwwsaBISkRjWynYbH4YDaLVknGBsBw6L0ufeqZ883DKiyg5xIu+XNUDDTD+/Kau6jQfdOE3Y9aMqCWoBdGTGl1Wbg70WW6zurxvDzyTMHUYxGbaEE4Vz5eXPQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
