# create kustimization.yaml file
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Merge Patch https://stackoverflow.com/questions/76004172/how-to-add-init-container-with-kustomize

namespace: media

patches:
  - target:
      kind: Deployment
      namespace: media
    patch: |
      - op: add
        path: /spec/template/spec/nodeName
        value: media

resources:
- ../../../base/media
- ../../../config/production/media
- storage.yml
# - ingress.yml
- tunnel.yml