apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-local-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
  hostPath:
    path: /home/zek/Documents/Minikube/Media/Content # Example host path to simulate an empty directory
    type: DirectoryOrCreate


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-local-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 10Gi
  volumeName: media-local-storage

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-config-longhorn-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "standard"
  hostPath:
    path: /home/zek/Documents/Minikube/Media/Config # Example host path to simulate an empty directory
    type: DirectoryOrCreate


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-config-longhorn-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  resources:
    requests:
      storage: 10Gi
  volumeName: media-config-longhorn-storage

