apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://trstringer.com/helm-kustomize/

patches:
  - target:
      kind: Prometheus
      namespace: monitoring
    patch: |
      - op: add
        path: /spec/nodeSelector
        value: 
          nodetype: monitor
  - target:
      kind: Alertmanager
      namespace: monitoring
    patch: |
      - op: add
        path: /spec/nodeSelector
        value: 
          nodetype: monitor

resources:
  - helm-resource.yml