---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-storage
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "default"
  nfs:
    server: 10.0.0.146
    path: /volume1/k8data/storage/ai


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-storage-claim
  labels:
    backup: every-3-days
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "default"
  resources:
    requests:
      storage: 2Gi
  volumeName: ai-storage
