apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: jellyfin
        network-policy: media-viewer
    spec:
      runtimeClassName: nvidia # https://forum.jellyfin.org/t-enable-nvidia-hardware-transcode-on-k8s
      containers: 
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          envFrom:
            - configMapRef:
                name: time-zone
            - configMapRef:
                name: arr-user
          resources:
            requests:
              memory: 500M
              cpu: "0.50"
            limits: 
              memory: 1024M
              cpu: "1.5"
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: media-config-longhorn-storage
              mountPath: /config
              subPath: jellyfin
            - name: media-local-storage
              mountPath: /media/tv
              subPath: tv
            - name: media-local-storage
              mountPath: /media/movie
              subPath: movies
          # healthcheck: # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/        
      volumes:
        - name: media-config-longhorn-storage
          persistentVolumeClaim:
            claimName: media-config-longhorn-storage-claim
        - name: media-local-storage
          persistentVolumeClaim:
            claimName: media-local-storage-claim
      restartPolicy: Always
      serviceAccount: jellyfin

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  ports:
    - name: http-web-ui
      port: 7026
      protocol: TCP
      targetPort: 8096
  selector:
    app: jellyfin


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin
