---

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/mounting_an_smb_share
# https://linux.die.net/man/8/mount.cifs

# Can't be bothered anymore :/

# - name: Mount to SMB
#   become: true
#   ansible.posix.mount:
#     src: //10.0.0.11/Firefly-Information
#     path: "{{ firefly_smb_path }}"
#     opts: "rw,username={{ firefly_smb_username }},password={{ firefly_smb_password }}"
#     fstype: cifs
#     state: mounted
#     boot: true

- name: Copy env files to container
  become_user: "{{ ansible_user }}"
  ansible.builtin.template:
    mode: u=rw,g=r
    src: "{{ item.src }}"
    dest: "~/{{ item.name }}"
  loop: '{{ template_files }}'

- name: Create Firefly
  become_user: "{{ ansible_user }}"
  community.docker.docker_compose:
    project_name: Firefly
    project_src: "~/"
    env_file: firefly.env
    files:
      - "firefly.compose"

- name: Delete env files
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    path: "~/{{ item.name }}"
    state: absent
  loop: '{{ template_files }}'


# - name: Install CStorage
#   ansible.builtin.import_tasks:
#     cstorage.ansible.yml
#   when: "ansible_facts['hostname'] | lower == 'cstorage'"
