apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventscraper
  name: eventscraper
spec:
  selector: 
    matchLabels:
      app: eventscraper
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: eventscraper
    spec:
      containers: 
        - name: eventscraper
          image: localhost:31000/ct-event-scraper:latest
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          envFrom:
            - secretRef:
                name: eventscraper-secrets
            - configMapRef:
                name: eventscraper-env
          resources:
            requests:
              memory: 300M
              cpu: "0.10"
            limits: 
              memory: 400M
              cpu: "0.25"
          volumeMounts:
            - name: eventscraper-storage
              mountPath: /app/config
              subPath: eventscraper
      volumes:
        - name: eventscraper-storage
          persistentVolumeClaim:
            claimName: bot-storage-claim
      restartPolicy: Always

