apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leantime
  name: leantime
spec:
  selector: 
    matchLabels:
      app: leantime
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: leantime
    spec:
      containers: 
        - name: leantime
          image: leantime/leantime
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - secretRef:
                name: leantime-secrets
          env:
            - name: LEAN_DB_PORT
              value: '3306'
            - name: LEAN_DB_HOST
              value: 127.0.0.1 # Localhost refused to work 
            - name: LEAN_DB_DATABASE
              value: leantime
            - name: LEAN_DB_USER
              value: leantime
            - name: LEAN_SESSION_EXPIRATION
              value: '172800'
            - name: LEAN_APP_URL
              value: https://leantime.tunnel.homelab.ezequielvalencia.com

          resources:
          volumeMounts:
            - name: leantime-storage
              mountPath: /var/www/html/public/userfiles 
              subPath: leantime/public/userfiles
            - name: leantime-storage
              mountPath: /var/www/html/userfiles  
              subPath: leantime/userfiles
            - name: leantime-storage
              mountPath: /var/www/html/app/Plugins  
              subPath: leantime/plugins
            - name: leantime-storage
              mountPath: /var/www/html/storage/logs
              subPath: leantime/logs
        
        - name: mysql
          image: mysql:8.4
          # command: ["sleep", "3600"] # For Debugging
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 1000
            runAsGroup: 1000 
          envFrom:
            - secretRef:
                name: leantime-secrets
          env:
            - name: MYSQL_DATABASE
              value: leantime
            - name: MYSQL_USER
              value: leantime
          resources:
          volumeMounts:
            - name: leantime-storage
              mountPath: /var/lib/mysql
              subPath: leantime/db

      volumes:
        - name: leantime-storage
          persistentVolumeClaim:
            claimName: bot-storage-claim
      restartPolicy: Always
      nodeName: bots

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: leantime
  name: leantime
spec:
  ports:
    - name: http-leantime
      port: 80
      targetPort: 8080
  selector:
    app: leantime


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leantime
