---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ct-grassroots
  name: ct-grassroots
spec:
  selector: 
    matchLabels:
      app: ct-grassroots
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ct-grassroots
    spec:
      containers: 
        - name: ct-grassroots
          image: kaihuri/mobilizon:5.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          env:
            # - name: MIX_ENV
            #   value: prod mix release
            - name: MOBILIZON_LOGLEVEL
              value: error
            - name: MOBILIZON_INSTANCE_NAME 
              value: CTGrassRoots
            - name: MOBILIZON_INSTANCE_HOST
              value: ctgrassroots.org
            - name: MOBILIZON_INSTANCE_PORT
              value: '4000'
            - name: MOBILIZON_INSTANCE_REGISTRATIONS_OPEN
              value: "false"
            - name: MOBILIZON_INSTANCE_EMAIL

            # Mobilizon Database
            - name: MOBILIZON_DATABASE_USERNAME
              value: mobilizon
            - name: MOBILIZON_DATABASE_DBNAME
              value: ct-grassroots
            - name: MOBILIZON_DATABASE_HOST 
              value: postgres.database.homelab.ezequielvalencia.com
            - name: MOBILIZON_DATABASE_PORT
              value: "54333"
            - name: MOBILIZON_DATABASE_SSL
              value: "false"
          envFrom:
            - secretRef:
                name: mobilizon-secret
          resources:
            requests:
              memory: 300M
              cpu: "0.1"
            limits: 
              memory: 600M
              cpu: "0.5"
          volumeMounts:
            - name: mobilizon-storage
              mountPath: /var/lib/mobilizon/uploads
              subPath: ct-grassroots/uploads

            # - name: mobilizon-storage
            #   mountPath: /etc/mobilizon/config.exs
            #   subPath: ct-grassroots/config.exs
          
      volumes:
        - name: mobilizon-storage
          persistentVolumeClaim:
            claimName: mobilizon-storage-claim
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.0.0.6
      restartPolicy: Always
      serviceAccount: ct-grassroots

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ct-grassroots
  name: ct-grassroots
spec:
  ports:
    - name: website
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: ct-grassroots


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ct-grassroots

