---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ezequiel-backend
  name: ezequiel-backend
spec:
  selector: 
    matchLabels:
      app: ezequiel-backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ezequiel-backend
    spec:
      containers: 
        - name: ezequiel-backend
          image: localhost:31000/ezequiel-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          env:
            # All subdomains can also access this cookie
            - name: CORS_ALLOWED
              value: https://ezequielvalencia.com,https://d29w5rfwyyex3t.cloudfront.net
          envFrom:
            - secretRef:
                name: ezequiel-backend-secrets
          resources:
            requests:
              memory: 300M
              cpu: "0.10"
            limits: 
              memory: 700M
              cpu: "0.25"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.0.0.6
      restartPolicy: Always
      serviceAccount: ezequiel-backend


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ezequiel-backend
  name: ezequiel-backend
spec:
  ports:
    - name: backend
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: db
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: ezequiel-backend


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ezequiel-backend

